### ISSUE TITLE
Send email for the party

### ISSUE THREAD

**Issue by AnxhelaDani** [eamonnmag/leaving_party#4]
rcs-dep-sis-complete

**Comment by Panos512** [comment]
> Hello!
> 
> As our time at CERN is almost over, we would like to invite you to our farewell party to celebrate all the good times we have had here.
> It will take place on Monday, October 31st at 17:30 in R1.
> 
> We are looking forward to see you there :-)
> 
> Have a good weekend,
> 
> Anxhela Dani
> Eamonn Maguire
> Panos Paparrigopoulos


Is this ok guys? @AnxhelaDani  @eamonnmag

**Comment by AnxhelaDani** [comment]
👍
